#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: MIT

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../utils/colors.sh"
source "${SCRIPT_DIR}/../utils/git-utils.sh"
source "${SCRIPT_DIR}/../utils/mise-tool.sh"

# Shipped example organization-rules overlay (template - replace via a private
# overlay path for real internal hosts), used when DEVBASE_CHECK_ORG_RULES=1.
readonly ORG_RULES_DEFAULT="${SCRIPT_DIR}/config/org-rules.toml"

# Temp config generated by build_merged_config(); removed by the EXIT trap.
MERGED_CONFIG=""
cleanup_merged_config() {
  [[ -n "${MERGED_CONFIG}" && -f "${MERGED_CONFIG}" ]] && rm -f "${MERGED_CONFIG}"
  return 0
}
trap cleanup_merged_config EXIT

# Resolve the org-rules overlay selected by DEVBASE_CHECK_ORG_RULES.
# Prints the overlay path to use, or nothing when org rules are off.
#   unset / 0 / false / no / off -> off (opt-in default; prints nothing)
#   1 / true / yes / on          -> shipped overlay (config/org-rules.toml)
#   <path>                       -> a team-supplied overlay file
resolve_org_rules_overlay() {
  local sel="${DEVBASE_CHECK_ORG_RULES:-}"
  case "$sel" in
  "" | 0 | false | FALSE | no | NO | off | OFF) return 0 ;;
  1 | true | TRUE | yes | YES | on | ON) printf '%s' "$ORG_RULES_DEFAULT" ;;
  *) printf '%s' "$sel" ;;
  esac
}

# Generate a temp gitleaks config that layers the given org-rules overlay on
# top of the repo's existing configuration (gitleaks reads a single config):
#   - repo has a local .gitleaks.toml -> extend it (keeps its rules, allowlists
#     and its own useDefault), then append the overlay's rules
#   - no local config                 -> extend the gitleaks defaults, then append
# Prints the temp config path.
build_merged_config() {
  local overlay="$1"
  MERGED_CONFIG=$(mktemp "${TMPDIR:-/tmp}/devbase-gitleaks.XXXXXX.toml") || return 1
  {
    if [[ -f ".gitleaks.toml" ]]; then
      printf '[extend]\npath = "%s/.gitleaks.toml"\n\n' "$PWD"
    else
      printf '[extend]\nuseDefault = true\n\n'
    fi
    cat "$overlay"
  } >"$MERGED_CONFIG"
  printf '%s' "$MERGED_CONFIG"
}

main() {
  print_header "SECRET SCANNING (GITLEAKS)"
  fail_if_mise_install_incomplete gitleaks || return 1

  if ! command -v gitleaks >/dev/null 2>&1; then
    print_warning "gitleaks not found in PATH - skipping secret scanning"
    echo "  Install: mise install"
    emit_status "skip" "not in PATH"
    return 0
  fi

  # Opt-in: layer organization-specific rules on top of the repo's config.
  local overlay config_flag=""
  overlay=$(resolve_org_rules_overlay)
  if [[ -n "$overlay" ]]; then
    if [[ ! -f "$overlay" ]]; then
      print_error "DEVBASE_CHECK_ORG_RULES set but overlay not found: ${overlay}"
      emit_status "fail" "org-rules overlay missing"
      return 1
    fi
    local merged
    merged=$(build_merged_config "$overlay") || {
      print_error "Failed to build merged gitleaks config"
      emit_status "fail" "failed"
      return 1
    }
    config_flag="--config=${merged}"
    print_info "Org rules enabled - layering $(basename "$overlay") on top of repo config"
  fi

  local default_branch current_branch
  default_branch=$(get_default_branch)
  current_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

  local gitleaks_result
  if [[ "$current_branch" == "$default_branch" ]]; then
    print_info "On default branch, scanning all commits..."
    # shellcheck disable=SC2086
    gitleaks detect --source=. --verbose --redact=50 $config_flag
    gitleaks_result=$?
  elif branch_exists "$default_branch"; then
    print_info "Scanning commits different from ${default_branch}..."
    # shellcheck disable=SC2086
    gitleaks detect --source=. --log-opts="${default_branch}..HEAD" --verbose --redact=50 $config_flag
    gitleaks_result=$?
  else
    print_info "No base branch found, scanning all commits..."
    # shellcheck disable=SC2086
    gitleaks detect --source=. --verbose --redact=50 $config_flag
    gitleaks_result=$?
  fi

  if [[ $gitleaks_result -eq 0 ]]; then
    print_success "No secrets found"
    emit_status "pass" "ok"
    return 0
  else
    print_error "Secret scanning failed - secrets may be present!"
    emit_status "fail" "failed"
    return 1
  fi
}

main
